title: Slemgrim
email: contact@slemgrim.com
description: A blog about web technology, architecture, programming and unicorns.
baseurl: ""
url: "http://slemgrim.com"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

permalink: /:title

gems:
  - jekyll-sitemap
