title: slemgirm.com
email: slemgrim+blog@gmail.com
description: Personal blog of Markus Ritberger about web technologies
baseurl: ""
url: "http://slemgrim.com"
twitter_username: slemgrim
github_username:  slemgrim
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

permalink: /:title
